title: Vicente Manuel Muñoz Milchorena
repository: vicosurge/vicente-milchorena
email: vicente@milchorena.com
logo: assets/3.png
description: >-
  I am a Historian by training, an IT Professional from 15 years of experience,
  and an author of several books (none of which have my name, but that is the
  trade of a ghost writer).
baseurl: "/"
url: "https://vicente.milchorena.com"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-target-blank
